spring:
  application:
    name: crypto-trading-system
  datasource:
    url:  jdbc:postgresql://ep-rapid-rice-a5dqebw3.us-east-2.aws.neon.tech:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: testdb_owner
    password: svQg6Yl4tVzO
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema/h2init.sql
      data-locations: classpath:data/h2data.sql
# ===============================
# Binance
# ===============================
binance:
  service:
    host: https://api.binance.com
    getBinanceBookTickerUrl: ${binance.service.host}/api/v3/ticker/bookTicker

# ===============================
# Huobi
# ===============================
huobi:
  service:
    host: https://api.huobi.pro
    getHuobiMarketTickerUrl: ${huobi.service.host}/market/tickers

# ===============================
# Schedule to get data from sources - 60s
# ===============================
get:
  prices:
    fixed-rate:
      in:
        milliseconds: 60000