spring:
  application:
    name: crypto-trading-system
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema/h2init.sql
      data-locations: classpath:data/h2data.sql
# ===============================
# Binance
# ===============================
binance:
  service:
    host: https://api.binance.com
    getBinanceBookTickerUrl: ${binance.service.host}/api/v3/ticker/bookTicker

# ===============================
# Huobi
# ===============================
huobi:
  service:
    host: https://api.huobi.pro
    getHuobiMarketTickerUrl: ${huobi.service.host}/market/tickers

# ===============================
# Schedule to get data from sources - 10s
# ===============================
get:
  prices:
    fixed-rate:
      in:
        milliseconds: 10000